server:
  port: 8761
  display-name: eurekaServer
  contextPath: /eurekaServer

spring:
  application:
    name: ${server.display-name}

security:
  basic:
    enabled: true #开启认证
  user:
    name: guest
    password: guest

  #注册中心地址
eureka:
  server:
    enable-self-preservation: false
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eurekaServer/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    ip-address: localhost
    non-secure-port: 5006
    instance-id: eureka:${eureka.instance.ip-address}:${eureka.instance.non-secure-port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


management:
  security:
    enabled: false


endpoints:
  sensitive: false
  shutdown:
    enabled: true

